#!/bin/bash
code --install-extension 13xforever.language-x86-64-assembly
code --install-extension abusaidm.html-snippets
code --install-extension ajhyndman.jslint
code --install-extension codezombiech.gitignore
code --install-extension cometeer.spacemacs
code --install-extension Dart-Code.dart-code
code --install-extension dbaeumer.vscode-eslint
code --install-extension felixfbecker.php-intellisense
code --install-extension flowtype.flow-for-vscode
code --install-extension formulahendry.vscode-mysql
code --install-extension gogocrow.webpack-snippets
code --install-extension hangxingliu.vscode-nginx-conf-hint
code --install-extension HookyQR.beautify
code --install-extension jeremyrajan.webpack
code --install-extension lukasz-wronski.ftp-sync
code --install-extension MehediDracula.php-namespace-resolver
code --install-extension mrmlnc.vscode-scss
code --install-extension ms-vscode.cpptools
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension negokaz.live-server-preview
code --install-extension neilbrayfield.php-docblocker
code --install-extension nhoizey.gremlins
code --install-extension phproberto.vscode-php-getters-setters
code --install-extension PKief.material-icon-theme
code --install-extension rafaelmaiolla.remote-vscode
code --install-extension rust-lang.rust
code --install-extension sachittandukar.laravel-5-snippets
code --install-extension saviorisdead.RustyCode
code --install-extension shanoor.vscode-nginx
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension stevencl.addDocComments
code --install-extension Valiantsin.fixmyjs
code --install-extension walter-ribeiro.full-react-snippets
code --install-extension wengerk.highlight-bad-chars
code --install-extension yzane.markdown-pdf
code --install-extension yzhang.markdown-all-in-one
code --install-extension zeeshanu.livereload
code --install-extension Zignd.html-css-class-completion
