code --install-extension 13xforever.language-x86-64-assembly
code --install-extension aaron-bond.better-comments
code --install-extension abusaidm.html-snippets
code --install-extension ajhyndman.jslint
code --install-extension alefragnani.Bookmarks
code --install-extension alefragnani.pascal
code --install-extension alefragnani.pascal-formatter
code --install-extension alefragnani.rtf
code --install-extension Angular.ng-template
code --install-extension atlassian.atlascode
code --install-extension bierner.markdown-preview-github-styles
code --install-extension bmewburn.vscode-intelephense-client
code --install-extension bowlerhatllc.vscode-nextgenas
code --install-extension bowlerhatllc.vscode-swf-debug
code --install-extension charles-sanford.scss-block-comments
code --install-extension codezombiech.gitignore
code --install-extension cometeer.spacemacs
code --install-extension cschlosser.doxdocgen
code --install-extension Dart-Code.dart-code
code --install-extension Dart-Code.flutter
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension dracula-theme.theme-dracula
code --install-extension eamodio.gitlens
code --install-extension Equinusocio.vsc-community-material-theme
code --install-extension Equinusocio.vsc-material-theme
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension eric-c-hansen.vscode-docker-phpunit
code --install-extension esbenp.prettier-vscode
code --install-extension fabiospampinato.vscode-diff
code --install-extension felixfbecker.php-debug
code --install-extension felixfbecker.php-intellisense
code --install-extension felixrieseberg.vsc-travis-ci-status
code --install-extension flowtype.flow-for-vscode
code --install-extension formulahendry.vscode-mysql
code --install-extension foxundermoon.shell-format
code --install-extension funkyremi.vscode-google-translate
code --install-extension gogocrow.webpack-snippets
code --install-extension hangxingliu.vscode-nginx-conf-hint
code --install-extension hbenl.vscode-test-explorer
code --install-extension HookyQR.beautify
code --install-extension huacnlee.theme-blackboard-plus
code --install-extension IBMBlockchain.ibm-blockchain-platform
code --install-extension idleberg.innosetup
code --install-extension ikappas.phpcs
code --install-extension ipid.asm-comment-aligner
code --install-extension jbenden.c-cpp-flylint
code --install-extension jeremyrajan.webpack
code --install-extension jspolancor.presentationmode
code --install-extension junstyle.php-cs-fixer
code --install-extension k--kato.docomment
code --install-extension karyfoundation.theme-karyfoundation-themes
code --install-extension lukasz-wronski.ftp-sync
code --install-extension mads-hartmann.bash-ide-vscode
code --install-extension MehediDracula.php-namespace-resolver
code --install-extension mikestead.dotenv
code --install-extension momoto.binary-viewer
code --install-extension mrmlnc.vscode-scss
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-dotnettools.csharp
code --install-extension ms-python.python
code --install-extension ms-vscode.cpptools
code --install-extension ms-vscode.powershell
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension mwood0904.clear-console
code --install-extension negokaz.live-server-preview
code --install-extension neilbrayfield.php-docblocker
code --install-extension nhoizey.gremlins
code --install-extension NicholasHsiang.vscode-angularjs-snippet
code --install-extension NuclleaR.vscode-extension-auto-import
code --install-extension onecentlin.laravel-blade
code --install-extension Orta.vscode-jest
code --install-extension oshri6688.javascript-test-runner
code --install-extension phproberto.vscode-php-getters-setters
code --install-extension PKief.material-icon-theme
code --install-extension rafaelmaiolla.remote-vscode
code --install-extension redhat.java
code --install-extension redhat.vscode-xml
code --install-extension redhat.vscode-yaml
code --install-extension rust-lang.rust
code --install-extension sachittandukar.laravel-5-snippets
code --install-extension saviorisdead.RustyCode
code --install-extension sdras.night-owl
code --install-extension serayuzgur.crates
code --install-extension shanoor.vscode-nginx
code --install-extension shd101wyy.markdown-preview-enhanced
code --install-extension stepanog.angular1-inline
code --install-extension stevencl.addDocComments
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension teabyii.ayu
code --install-extension therobut.theme-setim
code --install-extension ThreadHeap.serverless-ide-vscode
code --install-extension Valiantsin.fixmyjs
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension walter-ribeiro.full-react-snippets
code --install-extension wengerk.highlight-bad-chars
code --install-extension yuichinukiyama.vscode-preview-server
code --install-extension yzane.markdown-pdf
code --install-extension yzhang.markdown-all-in-one
code --install-extension zhuangtongfa.material-theme
code --install-extension Zignd.html-css-class-completion
